spring.application.name=kafka-order-system
server.port=5000

# Kafka bootstrap server (Docker port 29092)
spring.kafka.bootstrap-servers=localhost:29092

# Schema Registry URL (new port 5001)
spring.kafka.properties.schema-registry-url=http://localhost:5001

# Kafka consumer group id
spring.kafka.consumer.group-id=order-consumer-group

# Kafka producer client id
spring.kafka.producer.client-id=order-producer

# Kafka topics
app.kafka.orders-topic=orders
app.kafka.dlq-topic=orders-dlq

# Optional: retry settings
app.kafka.retry-attempts=5
app.kafka.retry-backoff-ms=3000
